receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
        cors:
          allowed_origins:
            - http://localhost:3000
            - http://localhost:3301
            - https://*.madfam.io
  prometheus:
    config:
      scrape_configs:
        - job_name: 'otel-collector'
          scrape_interval: 10s
          static_configs:
            - targets: ['localhost:8888']
  jaeger:
    protocols:
      grpc:
        endpoint: 0.0.0.0:14250
      thrift_http:
        endpoint: 0.0.0.0:14268
  zipkin:
    endpoint: 0.0.0.0:9411

processors:
  batch:
    send_batch_size: 1000
    timeout: 10s
  memory_limiter:
    check_interval: 1s
    limit_mib: 2000
    spike_limit_mib: 200
  resource:
    attributes:
      - key: service.name
        from_attribute: service_name
        action: insert
      - key: service.version
        value: ${SERVICE_VERSION}
        action: upsert
      - key: deployment.environment
        value: ${DEPLOYMENT_ENV}
        action: upsert
  attributes:
    actions:
      - key: http.url
        action: delete
      - key: http.user_agent
        action: delete

exporters:
  clickhousetraces:
    endpoint: tcp://clickhouse:9000/?database=signoz_traces
    timeout: 10s
    retry_on_failure:
      enabled: true
      initial_interval: 5s
      max_interval: 30s
      max_elapsed_time: 300s
  clickhousemetricswrite:
    endpoint: tcp://clickhouse:9000/?database=signoz_metrics
    resource_to_telemetry_conversion:
      enabled: true
  clickhouselogsexporter:
    endpoint: tcp://clickhouse:9000/?database=signoz_logs
    timeout: 10s
  prometheusremotewrite:
    endpoint: http://prometheus:9090/api/v1/write
  logging:
    loglevel: debug

extensions:
  health_check:
    endpoint: 0.0.0.0:13133
  pprof:
    endpoint: localhost:1777
  zpages:
    endpoint: localhost:55679

service:
  extensions: [health_check, pprof, zpages]
  pipelines:
    traces:
      receivers: [otlp, jaeger, zipkin]
      processors: [batch, memory_limiter, resource, attributes]
      exporters: [clickhousetraces]
    metrics:
      receivers: [otlp, prometheus]
      processors: [batch, memory_limiter, resource]
      exporters: [clickhousemetricswrite]
    logs:
      receivers: [otlp]
      processors: [batch, memory_limiter, resource]
      exporters: [clickhouselogsexporter]
