name: License Compliance Check

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  check-license:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Check License Headers
        run: |
          echo "🔍 Checking for proper license headers..."
          pnpm check:license

      - name: Verify LICENSE.md unchanged
        if: github.event_name == 'pull_request'
        run: |
          echo "🔒 Verifying license files haven't been modified..."
          git diff origin/${{ github.base_ref }} -- LICENSE.md LICENSE-*.md
          if git diff origin/${{ github.base_ref }} -- LICENSE.md LICENSE-*.md | grep -q .; then
            echo "❌ ERROR: License files have been modified!"
            echo "License file modifications require explicit approval from MADFAM."
            exit 1
          fi
          echo "✅ License files unchanged"

      - name: Check for commercial use indicators
        run: |
          echo "🔍 Scanning for potential commercial use indicators..."

          # Check for production deployment configs
          if find . -name "*.yml" -o -name "*.yaml" | xargs grep -l "production" | grep -v ".github" | grep -v "test"; then
            echo "⚠️  WARNING: Production configuration files detected"
            echo "Ensure these are not for unauthorized commercial deployment"
          fi

          # Check for payment processing code
          if find . -name "*.ts" -o -name "*.tsx" -o -name "*.js" -o -name "*.jsx" | xargs grep -l "stripe\|payment\|subscription" | grep -v "test" | grep -v "mock"; then
            echo "⚠️  WARNING: Payment processing code detected"
            echo "Commercial features require proper licensing"
          fi

      - name: Scan for license violations
        run: |
          echo "🔍 Scanning for potential license violations..."

          # Check for removed license headers
          if git diff HEAD~ -- '*.ts' '*.tsx' '*.js' '*.jsx' | grep -E "^-.*MADFAM Code Available License" > /dev/null; then
            echo "❌ ERROR: License headers have been removed!"
            exit 1
          fi

          # Check for competing product names
          if find . -name "*.ts" -o -name "*.tsx" -o -name "*.js" -o -name "*.jsx" | xargs grep -i "portfolio\s*builder\|cv\s*builder" | grep -v "PRISMA\|MADFAM" | grep -v "test"; then
            echo "⚠️  WARNING: Potential competing product references detected"
          fi

          echo "✅ No license violations detected"
